/rat/db/set DETECTOR experiment "minicaptain"
/rat/db/set DETECTOR geo_file "minicaptain/minicaptain.geo"

/run/initialize

# BEGIN EVENT LOOP
/rat/proc count
/rat/procset update 10
/rat/proc prune
/rat/procset prune "ev"

/glg4scint/on
/glg4scint/reemission on

# Use IO.default_output_filename
/rat/proclast outroot
#END EVENT LOOP

/generator/add combo pbomb:point
/generator/vtx/set 10000 128
/generator/pos/set 0 0 -123.11

/run/beamOn 100
