/PhysicsList/setOpWLS g4

/rat/db/set DETECTOR experiment "minicaptain"
/rat/db/set DETECTOR geo_file "minicaptain/minicaptain.geo"

/run/initialize

# BEGIN EVENT LOOP
#/rat/proc simpledaq
/rat/proc count
/rat/procset update 1

/glg4scint/on
/glg4scint/reemission on

# Use IO.default_output_filename
/rat/proclast outroot
/rat/procset file "demo.root"
#END EVENT LOOP

#/generator/add combo pbomb:point
#/generator/vtx/set 1000 128
#/generator/pos/set 0 0 -123.11
/generator/add combo gun2:point
/generator/vtx/set neutron -1 0 0 1 10 800
/generator/pos/set 610 0 -123.11

/run/beamOn 100
