#set the detector parameters
/rat/db/set DETECTOR experiment "minicaptain"
/rat/db/set DETECTOR geo_file "minicaptain/minicaptain.geo"

/run/initialize

#initialize the visualizer
/vis/open HepRepXML
/vis/scene/create
/vis/scene/add/volume
/vis/sceneHandler/attach
/vis/scene/add/trajectories
/vis/scene/add/hits
/tracking/discardParticleTrajectory opticalphoton
/tracking/storeTrajectory 1
/tracking/FillPointCont true

/glg4scint/on
/glg4scint/reemission on

# BEGIN EVENT LOOP
#/rat/proc simpledaq
/rat/proc count
/rat/procset update 1

/rat/proclast outroot
/rat/procset file "test.root"
#END EVENT LOOP

/generator/add combo gun2:point
/generator/vtx/set neutron  -1 0 0 10 800.0 800.0
/generator/pos/set 610 0 -123.11

#/generator/add combo pbomb:point
#/generator/vtx/set 100 128
#/generator/pos/set 0 0 -123.11

/run/beamOn 3
